/*389. Find the Difference
You are given two strings s and t.String t is generated by random shuffling string s and then add one more letter at a random position.Return the letter that was added to t.
Example 1: Input: s = "abcd", t = "abcde" Output: "e" Explanation: 'e' is the letter that was added.*/

class FindTheDifference389
{
	public static void main(String x[])
	{
		String s = "abcd", t = "abcde" ;
		System.out.println(findTheDifference(s,t));
	}
	public static char findTheDifference(String s, String t) 
	{
        int[] freq = new int[26];
		for(int i = 0 ; i < s.length() ; i++)
		{
			freq[s.charAt(i)-'a']++;
		}
		for(int i = 0 ; i < t.length() ; i++)
		{
			freq[t.charAt(i)-'a']--;
			if(freq[t.charAt(i)-'a'] < 0)
				return t.charAt(i); 
		}
		return ' ';
    }	
}